# GITLAB CI
#

stages: 
  - test

test:
    stage: test
    image: registry.pic.orangeportails.net/build-images/go16
    before_script: #
        - export CLAIR_PATH=/gopath/src/github.com/coreos/clair
        - sudo apt-get update
        - sudo apt-get install -y postgresql postgresql-contrib gcc build-essential rpm
        - mkdir -p "${CLAIR_PATH}"
        - export GOPATH=/gopath/
        - mv * ${CLAIR_PATH}
        - cd "${CLAIR_PATH}"
        #- 'echo "local   all     all                     peer map=root_as_others" >> /etc/postgresql/9.5/main/pg_hba.conf'
        #- 'echo "host    all     all     127.0.0.1/32    ident map=root_as_others" >> /etc/postgresql/9.5/main/pg_hba.conf'
        #- 'echo "root_as_others  root            postgres" >> /etc/postgresql/9.5/main/pg_ident.conf'
        #- 'echo "root_as_others  root            gis" >> /etc/postgresql/9.5/main/pg_ident.conf'
        - /etc/init.d/postgresql start
        - sudo -u postgres psql -c "ALTER USER postgres PASSWORD '';"


    script: 
        - sudo -u postgres psql
        - go test -v $(go list ./... | grep -v /vendor/) 
